spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


# ==========================================
# CONFIGURAÇÃO DE OBSERVABILIDADE (ACTUATOR + PROMETHEUS)
# ==========================================
management:
  endpoints:
    web:
      exposure:
        # Por padrão, apenas 'health' fica exposto. 
        include: "health,prometheus"
  endpoint:
    health:
      # Opcional: Mostra detalhes do banco, disco, etc.
      show-details: always
  metrics:
    tags:
      # Cria uma tag global com o nome do serviço. 
      application: ${spring.application.name}